// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies;

public class Node
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject nodeMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MyFirstModule.Node";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		nodeID("nodeID"),
		name("name"),
		repulsion("repulsion"),
		shape("shape"),
		width("width"),
		height("height"),
		style("style"),
		imgUrl("imgUrl");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Node(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "MyFirstModule.Node"));
	}

	protected Node(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject nodeMendixObject)
	{
		if (nodeMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("MyFirstModule.Node", nodeMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a MyFirstModule.Node");

		this.nodeMendixObject = nodeMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Node.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static myfirstmodule.proxies.Node initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return myfirstmodule.proxies.Node.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static myfirstmodule.proxies.Node initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new myfirstmodule.proxies.Node(context, mendixObject);
	}

	public static myfirstmodule.proxies.Node load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return myfirstmodule.proxies.Node.initialize(context, mendixObject);
	}

	public static java.util.List<myfirstmodule.proxies.Node> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<myfirstmodule.proxies.Node> result = new java.util.ArrayList<myfirstmodule.proxies.Node>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//MyFirstModule.Node" + xpathConstraint))
			result.add(myfirstmodule.proxies.Node.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of nodeID
	 */
	public final java.lang.String getnodeID()
	{
		return getnodeID(getContext());
	}

	/**
	 * @param context
	 * @return value of nodeID
	 */
	public final java.lang.String getnodeID(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.nodeID.toString());
	}

	/**
	 * Set value of nodeID
	 * @param nodeid
	 */
	public final void setnodeID(java.lang.String nodeid)
	{
		setnodeID(getContext(), nodeid);
	}

	/**
	 * Set value of nodeID
	 * @param context
	 * @param nodeid
	 */
	public final void setnodeID(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String nodeid)
	{
		getMendixObject().setValue(context, MemberNames.nodeID.toString(), nodeid);
	}

	/**
	 * @return value of name
	 */
	public final java.lang.String getname()
	{
		return getname(getContext());
	}

	/**
	 * @param context
	 * @return value of name
	 */
	public final java.lang.String getname(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.name.toString());
	}

	/**
	 * Set value of name
	 * @param name
	 */
	public final void setname(java.lang.String name)
	{
		setname(getContext(), name);
	}

	/**
	 * Set value of name
	 * @param context
	 * @param name
	 */
	public final void setname(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String name)
	{
		getMendixObject().setValue(context, MemberNames.name.toString(), name);
	}

	/**
	 * @return value of repulsion
	 */
	public final java.lang.Integer getrepulsion()
	{
		return getrepulsion(getContext());
	}

	/**
	 * @param context
	 * @return value of repulsion
	 */
	public final java.lang.Integer getrepulsion(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.repulsion.toString());
	}

	/**
	 * Set value of repulsion
	 * @param repulsion
	 */
	public final void setrepulsion(java.lang.Integer repulsion)
	{
		setrepulsion(getContext(), repulsion);
	}

	/**
	 * Set value of repulsion
	 * @param context
	 * @param repulsion
	 */
	public final void setrepulsion(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer repulsion)
	{
		getMendixObject().setValue(context, MemberNames.repulsion.toString(), repulsion);
	}

	/**
	 * @return value of shape
	 */
	public final java.lang.String getshape()
	{
		return getshape(getContext());
	}

	/**
	 * @param context
	 * @return value of shape
	 */
	public final java.lang.String getshape(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.shape.toString());
	}

	/**
	 * Set value of shape
	 * @param shape
	 */
	public final void setshape(java.lang.String shape)
	{
		setshape(getContext(), shape);
	}

	/**
	 * Set value of shape
	 * @param context
	 * @param shape
	 */
	public final void setshape(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String shape)
	{
		getMendixObject().setValue(context, MemberNames.shape.toString(), shape);
	}

	/**
	 * @return value of width
	 */
	public final java.lang.Integer getwidth()
	{
		return getwidth(getContext());
	}

	/**
	 * @param context
	 * @return value of width
	 */
	public final java.lang.Integer getwidth(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.width.toString());
	}

	/**
	 * Set value of width
	 * @param width
	 */
	public final void setwidth(java.lang.Integer width)
	{
		setwidth(getContext(), width);
	}

	/**
	 * Set value of width
	 * @param context
	 * @param width
	 */
	public final void setwidth(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer width)
	{
		getMendixObject().setValue(context, MemberNames.width.toString(), width);
	}

	/**
	 * @return value of height
	 */
	public final java.lang.Integer getheight()
	{
		return getheight(getContext());
	}

	/**
	 * @param context
	 * @return value of height
	 */
	public final java.lang.Integer getheight(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.height.toString());
	}

	/**
	 * Set value of height
	 * @param height
	 */
	public final void setheight(java.lang.Integer height)
	{
		setheight(getContext(), height);
	}

	/**
	 * Set value of height
	 * @param context
	 * @param height
	 */
	public final void setheight(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer height)
	{
		getMendixObject().setValue(context, MemberNames.height.toString(), height);
	}

	/**
	 * @return value of style
	 */
	public final java.lang.String getstyle()
	{
		return getstyle(getContext());
	}

	/**
	 * @param context
	 * @return value of style
	 */
	public final java.lang.String getstyle(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.style.toString());
	}

	/**
	 * Set value of style
	 * @param style
	 */
	public final void setstyle(java.lang.String style)
	{
		setstyle(getContext(), style);
	}

	/**
	 * Set value of style
	 * @param context
	 * @param style
	 */
	public final void setstyle(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String style)
	{
		getMendixObject().setValue(context, MemberNames.style.toString(), style);
	}

	/**
	 * @return value of imgUrl
	 */
	public final java.lang.String getimgUrl()
	{
		return getimgUrl(getContext());
	}

	/**
	 * @param context
	 * @return value of imgUrl
	 */
	public final java.lang.String getimgUrl(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.imgUrl.toString());
	}

	/**
	 * Set value of imgUrl
	 * @param imgurl
	 */
	public final void setimgUrl(java.lang.String imgurl)
	{
		setimgUrl(getContext(), imgurl);
	}

	/**
	 * Set value of imgUrl
	 * @param context
	 * @param imgurl
	 */
	public final void setimgUrl(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String imgurl)
	{
		getMendixObject().setValue(context, MemberNames.imgUrl.toString(), imgurl);
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return nodeMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final myfirstmodule.proxies.Node that = (myfirstmodule.proxies.Node) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "MyFirstModule.Node";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
